### ISSUE TITLE
Redmine 3.x compatibility

### ISSUE THREAD

**Issue by zshahan** [ande3577/redmine_multi_column_custom_fields#14]
I am getting an error when attempting to run in redmine 3.0.1.

ActionView::Template::Error (undefined method `next_multi_column_index' for #<#<Class:0x000000055ea9e8>:0x000000039c5a60>):
     5: <div class="splitcontent">
     6: <div class="splitcontentleft">
     7: <% i = 0 %>
     8: <% next_multi_column = next_multi_column_index(:issue, i, @issue.editable_custom_field_values) %>
     9: <% split_on = (next_multi_column / 2.0).ceil - 1 %>
    10: <% @issue.editable_custom_field_values.each do |value| %>
    11:   <% if value.custom_field.multi_column %>
  app/views/issues/_attributes.html.erb:76:in `block in _app_views_issues__attributes_html_erb___3754421764828975508_48924680'
  app/helpers/application_helper.rb:1033:in `labelled_fields_for'
  app/views/issues/_attributes.html.erb:1:in `_app_views_issues__attributes_html_erb___3754421764828975508_48924680'
  app/views/issues/_form.html.erb:41:in `block in _app_views_issues__form_html_erb___2349855623153331030_47982220'
  app/helpers/application_helper.rb:1033:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___2349855623153331030_47982220'
  app/views/issues/new.html.erb:11:in `block in _app_views_issues_new_html_erb___2096361312687247694_45183620'
  app/helpers/application_helper.rb:1026:in `labelled_form_for'
  app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb___2096361312687247694_45183620'
  app/controllers/issues_controller.rb:130:in `block (2 levels) in new'
  app/controllers/issues_controller.rb:129:in `new'

**Comment by ande3577** [comment]
I am unable to reproduce either on the current master branch, or on 3.0.1 specifically.  Have you migrated your database and restarted your server after installing the plugin?

Can you include  your full list of installed plugins?  I can check to see if any of them appear likely to interfere.PS. Wow Rails4 has a lot of breaking changes.

**Comment by zshahan** [comment]
Yes.  I did a rake redmine:plugins:migrate and restarted.

Environment:
  Redmine version                3.0.1.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            2.3.3
  Filesystem
Redmine plugins:
  advanced_roadmap_v2            2.4.0
  redmine_bootstrap_kit          0.2.3
  redmine_category_watchers      0.0.1
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.0
  redmine_dashboard              2.5.0
  redmine_issue_reminder         0.0.1
  redmine_journal_folder         0.0.1
  redmine_multi_column_custom_fields 0.0.1
  redmine_wiki_extensions        0.7.0
  redmine_wiki_lists             0.0.4
  redmine_workflow_hidden_fields 0.2.0
  view_customize                 1.1.2

**Comment by joshualamorie** [comment]
I have successfully installed this on a bitnami redmine stack.

Environment:
  Redmine version                3.0.0.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.9
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  redmine_importer               1.0
  redmine_multi_column_custom_fields 0.0.1
  redmine_traceability           2.1
