### ISSUE TITLE
Error when rendering issue

### ISSUE THREAD

**Issue by maximkrusina** [ande3577/redmine_multi_column_custom_fields#20]
```
Started GET "/issues/19" for xxx at 2017-01-12 19:42:42 +0100
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"19"}
  Current user: xxx (id=1)
  Rendered issues/_action_menu.html.erb (5.6ms)
  Rendered issues/show.html.erb within layouts/base (53.7ms)
Completed 500 Internal Server Error in 172ms (ActiveRecord: 31.8ms)

ActionView::Template::Error (no implicit conversion of nil into String):
    68:     end
    69:   end
    70: end %>
    71: <%= render_custom_fields_rows(@issue) %>
    72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    73: </div>
    74: 
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:37:in `+'
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:37:in `block in render_custom_fields_rows_with_multi_column'
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:23:in `each'
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:23:in `render_custom_fields_rows_with_multi_column'
  app/views/issues/show.html.erb:71:in `_app_views_issues_show_html_erb__593456319675257707_48809040'
  app/controllers/issues_controller.rb:117:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:114:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by tiagobortolini** [comment]
Hi,
I have this issue too. Did you solve it?

Thanks a lot

**Comment by poxtihc** [comment]
Same error:
ActionView::Template::Error (no implicit conversion of nil into String):
    68:     end
    69:   end
    70: end %>
    71: <%= render_custom_fields_rows(@issue) %>
    72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    73: </div>
    74:
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:37:in `+'
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:37:in `block in render_custom_fields_rows_with_multi_column'
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:23:in `each'
  plugins/redmine_multi_column_custom_fields/lib/redmine_multi_column_custom_fields/issues_helper_patch.rb:23:in `render_custom_fields_rows_with_multi_column'
  app/views/issues/show.html.erb:71:in `_e95d09aea911ef00097a3fbfb8377688'
  app/controllers/issues_controller.rb:117:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:114:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
